"""
Gemini AI service — handles all AI-powered analysis.
"""
import os
import re
import json
import asyncio
from google import genai
from dotenv import load_dotenv

load_dotenv()

current_key_index = 0

def get_api_keys():
    keys = [k.strip() for k in os.getenv("GEMINI_API_KEY", "").split(",") if k.strip()]
    if not keys:
        raise ValueError("GEMINI_API_KEY environment variable is missing or empty. Please add it to your Vercel Environment Variables.")
    return keys

def get_client():
    """Get a Gemini client using the currently active API key."""
    keys = get_api_keys()
    return genai.Client(api_key=keys[current_key_index % len(keys)])


PROMPTS = {
    "ai_content": """
You are an expert AI content detector. Analyze the following text and determine how much of it was generated by AI.

Text to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = fully AI generated>,
  "verdict": "<'Likely AI Generated' | 'Possibly AI Generated' | 'Likely Human Written' | 'Mixed Content'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "ai_patterns_found": <number>,
    "human_patterns_found": <number>,
    "sentence_uniformity": <number 0-100>,
    "vocabulary_diversity": <number 0-100>
  }},
  "highlights": ["<specific phrase or pattern that triggered detection>", ...],
  "improvements": ["<suggestion to make text more human>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
""",

    "plagiarism": """
You are an expert plagiarism and originality detector. Analyze the following project/idea/text for originality.

Text to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = fully plagiarized / not original>,
  "verdict": "<'Highly Original' | 'Mostly Original' | 'Partially Copied' | 'Largely Copied'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "originality_score": <number 0-100>,
    "idea_uniqueness": <number 0-100>,
    "phrasing_uniqueness": <number 0-100>,
    "structural_creativity": <number 0-100>
  }},
  "highlights": ["<specific phrase or idea that appears non-original>", ...],
  "improvements": ["<suggestion to improve originality>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
""",

    "idea_check": """
You are an expert startup advisor and tech evaluator. Analyze the following project idea to determine if it is truly new/unique, or if it already exists in the market. If it exists, provide examples of who is already doing it and suggest what new features or pivots the user could add to make their idea authentic and unique.

Idea to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = completely unoriginal/already exists exactly>,
  "verdict": "<'Highly Unique' | 'Exists but has potential' | 'Already Common' | 'Exact Duplicate'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "market_saturation": <number 0-100>,
    "uniqueness_factor": <number 0-100>,
    "feasibility": <number 0-100>
  }},
  "highlights": ["<name of existing similar projects/companies>", ...],
  "improvements": ["<specific pivot or new feature to add to make it unique>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation of the market landscape for this idea>"
}}
""",

    "fake_news": """
You are an expert fact-checker and fake news detector. Analyze the following news article or content for credibility.

Content to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = definitely fake/misinformation>,
  "verdict": "<'Credible' | 'Questionable' | 'Likely Misleading' | 'Fake News'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "factual_accuracy": <number 0-100>,
    "source_credibility": <number 0-100>,
    "emotional_manipulation": <number 0-100>,
    "logical_consistency": <number 0-100>
  }},
  "highlights": ["<specific claim or phrase that is suspicious>", ...],
  "improvements": ["<what would make this more credible>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
""",

    "fake_review": """
You are an expert in detecting fake, bot-generated, or incentivized product reviews. Analyze the following review(s).

Review(s) to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = definitely fake>,
  "verdict": "<'Genuine Review' | 'Suspicious Review' | 'Likely Fake' | 'Bot Generated'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "language_naturalness": <number 0-100>,
    "specificity": <number 0-100>,
    "sentiment_authenticity": <number 0-100>,
    "pattern_repetition": <number 0-100>
  }},
  "highlights": ["<specific phrase or pattern that triggered suspicion>", ...],
  "improvements": ["<what a genuine review would include>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
""",

    "fake_profile": """
You are an expert in detecting fake social media profiles, bots, and inauthentic accounts. Analyze the following profile bio/information.

Profile info to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = definitely fake/bot>,
  "verdict": "<'Likely Real Person' | 'Suspicious Profile' | 'Likely Fake' | 'Bot Account'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "bio_authenticity": <number 0-100>,
    "language_naturalness": <number 0-100>,
    "information_consistency": <number 0-100>,
    "bot_pattern_score": <number 0-100>
  }},
  "highlights": ["<specific element that appears fake or bot-like>", ...],
  "improvements": ["<what a real profile bio would include>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
""",

    "fake_job": """
You are an expert in detecting scam job postings and fraudulent employment offers. Analyze the following job posting.

Job posting to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = definitely a scam>,
  "verdict": "<'Legitimate Posting' | 'Slightly Suspicious' | 'Likely Scam' | 'Definite Scam'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "company_legitimacy": <number 0-100>,
    "offer_realism": <number 0-100>,
    "language_professionalism": <number 0-100>,
    "red_flag_count": <number>
  }},
  "highlights": ["<specific red flag in the posting>", ...],
  "improvements": ["<what makes a legitimate job posting>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
""",

    "phishing": """
You are a cybersecurity expert specializing in phishing and email scam detection. Analyze the following email or message.

Content to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = definitely phishing>,
  "verdict": "<'Safe' | 'Suspicious' | 'Likely Phishing' | 'Confirmed Phishing'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "urgency_manipulation": <number 0-100>,
    "link_suspicion": <number 0-100>,
    "sender_legitimacy": <number 0-100>,
    "grammar_issues": <number 0-100>
  }},
  "highlights": ["<specific phishing indicator found>", ...],
  "improvements": ["<what to watch out for>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
""",

    "code_plagiarism": """
You are an expert code reviewer specializing in detecting plagiarized or AI-generated code. Analyze the following code.

Code to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = fully plagiarized or AI generated>,
  "verdict": "<'Original Code' | 'Possibly Copied' | 'Likely Plagiarized' | 'AI Generated Code'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "originality": <number 0-100>,
    "ai_generation_likelihood": <number 0-100>,
    "code_quality": <number 0-100>,
    "pattern_uniqueness": <number 0-100>
  }},
  "highlights": ["<specific code pattern that is suspicious>", ...],
  "improvements": ["<suggestion to make code more original>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
""",

    "general": """
You are a universal fake content detector. Analyze the following content for authenticity and legitimacy.

Content to analyze:
\"\"\"
{content}
\"\"\"

Respond ONLY with valid JSON in exactly this format:
{{
  "score": <number 0-100, where 100 = definitely fake/inauthentic>,
  "verdict": "<'Authentic' | 'Questionable' | 'Likely Fake' | 'Definitely Fake'>",
  "confidence": "<'High' | 'Medium' | 'Low'>",
  "breakdown": {{
    "authenticity": <number 0-100>,
    "consistency": <number 0-100>,
    "credibility": <number 0-100>,
    "red_flag_score": <number 0-100>
  }},
  "highlights": ["<specific element that triggered suspicion>", ...],
  "improvements": ["<suggestion>", ...],
  "raw_analysis": "<2-3 sentence detailed explanation>"
}}
"""
}


async def analyze_content(content: str, detection_type: str) -> dict:
    """Send content to Gemini for analysis with automatic API key rotation on rate limits."""
    global current_key_index
    prompt_template = PROMPTS.get(detection_type, PROMPTS["general"])
    
    # Inject Task 1 & 5 requirements into the expected JSON format
    prompt_template = prompt_template.replace(
        '"confidence": "<\'High\' | \'Medium\' | \'Low\'>",',
        '"confidence": "<\'High\' | \'Medium\' | \'Low\'>",\n  "language": "<detected language>",\n  "granularity": "<\'span-level\' | \'region-level\' | \'document-level only\'>",\n  "evidence": ["<exact text span or evidence>"],'
    )
    prompt_template += "\nIMPORTANT: If the detected language is not supported, set verdict to 'Unsupported Language'."

    prompt = prompt_template.format(content=content[:8000])  # Limit content length
    
    try:
        keys = get_api_keys()
        max_retries = len(keys)
    except ValueError as e:
        raise Exception(str(e))
        
    attempts = 0

    while attempts < max_retries:
        try:
            client = get_client()
            # Use async client so we don't block the FastAPI event loop
            response = await client.aio.models.generate_content(
                model="gemini-flash-latest",
                contents=prompt
            )
            raw_text = response.text.strip()

            # Clean markdown code blocks if present
            if raw_text.startswith("```"):
                raw_text = raw_text.split("```")[1]
                if raw_text.startswith("json"):
                    raw_text = raw_text[4:]
                raw_text = raw_text.strip()

            # Extract the JSON object even if there's trailing text
            match = re.search(r'\{.*\}', raw_text, re.DOTALL)
            if match:
                raw_text = match.group(0)

            result = json.loads(raw_text)
            result["detection_type"] = detection_type
            return result
            
        except Exception as e:
            error_msg = str(e)
            retryable_errors = ("429", "RESOURCE_EXHAUSTED", "503", "UNAVAILABLE", "403", "PERMISSION_DENIED")
            if any(code in error_msg for code in retryable_errors):
                attempts += 1
                if attempts < max_retries:
                    # Rotate to the next API key and retry (non-blocking)
                    await asyncio.sleep(1)
                    current_key_index = (current_key_index + 1) % max_retries
                    print(f"API Error ({error_msg[:30]}...). Rotating to API key index {current_key_index}...")
                    continue
                else:
                    raise Exception("All available API keys have exhausted their rate limits or the API is currently down due to high demand. Please try again in a few minutes.")
            
            # If it's a JSON parse error or something else, handle it below
            if isinstance(e, json.JSONDecodeError):
                break
            
            raise Exception(f"Gemini API error: {error_msg}")

    # If we break out of the loop, it means all keys are exhausted or we hit a parsing error
    return {
        "detection_type": detection_type,
        "score": 50,
        "verdict": "Analysis Inconclusive",
        "confidence": "Low",
        "language": "unknown",
        "granularity": "document-level only",
        "evidence": [],
        "breakdown": {},
        "highlights": [],
        "improvements": ["Please try again with clearer content."],
        "raw_analysis": "The AI was unable to parse the content properly or rate limits were exhausted."
    }
